name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Install YandexCloud CLI
      run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - name: Source YandexCloud CLI
      run: source /home/runner/.bashrc
    - name: Check $PATH
      run: echo $PATH
